name: ci
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - run: uv venv
        working-directory: moneypy
      - run: uv run make install
        working-directory: moneypy
      - run: uv run make format-check
        working-directory: moneypy
